# Generated by Django 2.2 on 2019-04-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_card_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_img',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
