# Generated by Django 2.1.7 on 2019-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
